### ISSUE TITLE
Segmentation Fault while using lammps

### ISSUE THREAD

**Issue by vsumaria** [CompPhysVienna/n2p2#104]
**The question**
I have a trained potential and am trying to use the potential to do some MD simulations. The training and validation process is working correctly. But when I use the potential for any structure (even for minimization), I am getting segmentation fault.

**What did you already try?**
Since segmentation fault is generally related to memory issues, I have tried to increase the memory while running the job, but i still am getting the same error. I tried to use a small structure (thinking that memory usage might reduce), but still have the same issue.  
The Element mapping string gets read, and the code stops. 

(I have attached here the input.nn, scaling.data, weight files and the laamps input files here. The structure is a simple Pt bulk structure (in the data.static file) and the pot.mod file contains the pair_style and pair_coeff lines)

[scaling.data.txt](https://github.com/CompPhysVienna/n2p2/files/6256382/scaling.data.txt)
[in.txt](https://github.com/CompPhysVienna/n2p2/files/6256370/in.txt)
[input.nn.txt](https://github.com/CompPhysVienna/n2p2/files/6256375/input.nn.txt)
[weights.006.data.txt](https://github.com/CompPhysVienna/n2p2/files/6256376/weights.006.data.txt)
[weights.008.data.txt](https://github.com/CompPhysVienna/n2p2/files/6256377/weights.008.data.txt)
[weights.078.data.txt](https://github.com/CompPhysVienna/n2p2/files/6256379/weights.078.data.txt)
[data.static.txt](https://github.com/CompPhysVienna/n2p2/files/6256387/data.static.txt)
[pot.mod.txt](https://github.com/CompPhysVienna/n2p2/files/6256388/pot.mod.txt)

**Comment by vsumaria** [comment]
Ok, having debugged this a little, I understand where the error is coming from. The potential is trained on 3 atom types - Pt, C, O; and I am using the potential to optimize a simple bulk Pt system. I think the way I am reading the files for lammps is causing the issue. 

I tried to use the same input files for a structure with all the three elements and it worked correctly. What might be going wrong when using just one element system?

**Comment by singraber** [comment]
There was indeed a bug as the code should have shown an error like this in your setup:
```
ERROR: LAMMPS type "2" not present, there are only 1 types defined.
```
instead of just segfaulting. However, on top of that small bug, a setup like yours, where there are less LAMMPS types than there are NNP elements was not considered yet and therefore the code would have exited with the above error anyway. However, since I think that there should be no problem in such a setup, I have modified the code in the latest commit to make it more permissive. So it should work now with your files, please report if that fixed it for you!
