### ISSUE TITLE
Lost Atoms

### ISSUE THREAD

**Issue by vsumaria** [CompPhysVienna/n2p2#110]
**The question**
While performing NPT MD simulations (using Lammps) with the n2p2 trained potential, very quickly leads to Lost Atoms error. What would be the suggestions to improve this NN potential. Anyone else face this issue ? 

**What did you already try?**
I have tried the following things:
1. Used nnp-comp2 to compare multiple NNP models and add more training data accordingly
2. Used different NNP architectures. - by changing the number of SF
3. Added structures into training set that exhibit high error (both for energy & forces) 

I have not tried changing the number of hidden layers - should that make a difference? 

**Background**
I am trying to model bulk alloying system. The training data consists of aimd data from nve (various temperatures), npt (few temperatures), elemental data (relaxation, strained).

**Comment by singraber** [comment]
Hello!

Sorry for the late reply! I cannot say for sure but most likely you just need to make your NNP more robust to work under the given conditions (NpT). The steps you have taken are already good but I guess you need more training data in particular for NpT. It's important to include data at higher temperatures (if possible/stable) than the ones your are interested in your production runs. Also it's a good idea to include lower and higher densities as well if you want a robust NNP for NpT.

I don't think changing the number of hidden layers will give much of a benefit.. what is your actual setup, can you provide an `input.nn` file? And maybe a log file from your LAMMPS runs?

Best,
Andreas
