### ISSUE TITLE
Error using nnp-norm

### ISSUE THREAD

**Issue by Matheus-Novoa** [CompPhysVienna/n2p2#124]
I'm facing a problem with nnp-norm. The structures present in "input.data" aren't being detected.

This can be seen in log file: "Total number of structures: 0". I compared with the data set file in the examples folder of n2p2 package and the structure of the file is consistent.

[input.nn.txt](https://github.com/CompPhysVienna/n2p2/files/7101695/input.nn.txt)
[nnp-norm.log.txt](https://github.com/CompPhysVienna/n2p2/files/7101696/nnp-norm.log.txt)
[input.data.txt](https://github.com/CompPhysVienna/n2p2/files/7101697/input.data.txt)

**Comment by moabe75** [comment]
Remove the blank line at the end of the "input.data" file. This should resolve your problem.

**Comment by Matheus-Novoa** [comment]
I already solved this issue. The problem was the difference between unix and windows text files formats.
