### ISSUE TITLE
Symmetry Functions

### ISSUE THREAD

**Issue by Matheus-Novoa** [CompPhysVienna/n2p2#129]
Is there any metric to define the parameters set of symmetry functions?

Parameters like cutoff distance, the radial functions parameters as well as the angular ones, and also the number of  symmetry functions for each pairwise elements in the system.

I found in literature no algorithm or metric, which could be used to do it.

**Comment by singraber** [comment]
This is indeed not a trivial task.. please have a look at "Step 4" in the [training documentation](https://compphysvienna.github.io/n2p2/topics/training.html#step-4-symmetry-function-setup). In particular look at references 3 and 4 on this page.. the automatic symmetry function generation according to the two schemes presented in the papers is implemented in the tool mentioned in the "Note" box.
