### ISSUE TITLE
Can N2P2 now use the long range interactions in lammps?

### ISSUE THREAD

**Issue by yugang-hello** [CompPhysVienna/n2p2#155]
Hi, I wonder if N2P2 could now achieve the long range interactions in lammps. I have seen issue #122 , it looks like this function will be available soon?

Thanks in advance for any responses.

**Comment by singraber** [comment]
Hi, there has been good progress recently, but unfortunately the implementation is not yet finished. If it's ready for production the PR's will be merged and a new release will be created.

**Comment by yugang-hello** [comment]
That's great, I'm really looking forward to using this function! Thank you for your great job!
