### ISSUE TITLE
ASE (atomic simulation environment) lammps calculator with n2p2

### ISSUE THREAD

**Issue by mastricker** [CompPhysVienna/n2p2#16]
I am trying to use an existing library which calculates all sorts of material parameters with n2p2.
It works with with an MEAM-type potential, but not with n2p2 somehow.

The solution would of course be that it works.

The library can be found here:
[gitlab link](https://gitlab.com/mstricker/evalpot)
In the folder `scripts` is a script with name `minimal_example_n2p2.py`, which should show the issue.
You need lammps compiled with `make mpi mode=shlib` and the python library `ase`.
If have enforced error messages in the lammps python api, but that did not help.

I first had the idea that maybe it is the atom types, which have to be different when working with n2p2 (ordered 1,2,3, not the atomic numbers), but that did not change the problem.

**Comment by mastricker** [comment]
Update: When using a different calculator in ASE, the `lammpslib`-calculator I can extract a (correct) potential energy. But when applying a filter, i.e. relaxation of a box, if segfaults.

**Comment by mastricker** [comment]
Lammps version: `patch_19Jul2019`
ASE version `3.17.0`

**Comment by mastricker** [comment]
Update again: using the `lammpslib`-calculator works now in the supplied minimal example. One needs to add `keep_alive=True`, my mistake.

But the `lammpsrun` version of ase does not work yet.

So maybe you can decide if you want that or not.

**Comment by vsumaria** [comment]
@mastricker -- can you help me out here. How did you end up using N2P2 with ase ?

**Comment by mastricker** [comment]
A lot has changed since more than two year. But the official documentation should be sufficient.
You need to compile it with lammps and then depending on how you want to use it in ASE, you either need the shared library version (which needs some manual fiddling) or not.
