### ISSUE TITLE
nnp-predict

### ISSUE THREAD

**Issue by ZengZezhu** [CompPhysVienna/n2p2#174]
Hi,

I just noticed that nnp-predict can only predict one configuration for each time, is it possible to predict multiple configurations in input.data at once? For example, I want to check the accuracy of NNPs to predict some (e.g., 100 configs) testing configurations, it  is inconvenient to use nnp-predict one by one.  Many thanks for your help in advance.

Cheers,
zezhu

**Comment by singraber** [comment]
Hello!

That's what the tool `nnp-dataset` is good for, e.g. like this:

```
mpirun -np 16 nnp-dataset 0
```
This will compute the predictions for all structures in `input.data` while distributing the work onto 16 MPI tasks. The `0` argument tells it not to shuffle the structures internally. Enabling this with `1` may yield better load balancing but the output order will then also be randomized.

Best,
Andreas

**Comment by ZengZezhu** [comment]
Thank you Andreas! I got it.

Cheers,
zezhu
