### ISSUE TITLE
pynnp: python3 error

### ISSUE THREAD

**Issue by PrabhakarBhimalapuram** [CompPhysVienna/n2p2#18]
**Describe the bug**
Regarding "pynnp": I am running the given verbose example.  the command "m.loadSettingsFile(input.nn)" is throwing TypeError. I looked around and it seems it is related to how Python3 deals with 'str' / 'byte' input...

Any pointers on how to fix this so that "input.nn" is loaded? 
I am using the latest version of n2p2 and python-3.7.3

**To Reproduce**: Below is the code..
import pynnp
cd ~/Projects/n2p2-master/examples/pynnp/prediction

# Initialize NNP setup (symmetry functions only).
m = pynnp.Mode()
m.initialize()
m.loadSettingsFile("input.nn")

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-274fb6e8bf8d> in <module>
----> 1 m.loadSettingsFile("input.nn")

pynnp.pyx in pynnp.Mode.loadSettingsFile()

~/Projects/n2p2-master/lib/pynnp.cpython-37m-x86_64-linux-gnu.so in string.from_py.__pyx_convert_string_from_py_std__in_string()

TypeError: expected bytes, str found

**Comment by singraber** [comment]
Thanks for reporting this.. it seems I missed this problem when switching from python 2 to 3. Indeed it comes from different default behavior when converting between Python 3 and C++ strings/bytes. I found this related chapter in the Cython docs here:

https://cython.readthedocs.io/en/latest/src/tutorial/strings.html#auto-encoding-and-decoding

So I added the `c_string_type=unicode` and `c_string_encoding=utf8` compiler directives in the latest commit (da93a7fe887e52fbc4fdfc2531e3ac964187f463), which solved the problem for me.

Can you confirm this? Thank you!

**Comment by PrabhakarBhimalapuram** [comment]
Thank you, that solved this problem for me. Appreciate the quick response.
 Closing this.
