### ISSUE TITLE
example-verbose

### ISSUE THREAD

**Issue by PrabhakarBhimalapuram** [CompPhysVienna/n2p2#19]
**Describe the bug**
I am running the given example "example-verbose" for pynnp and the command
m.setupSymmetryFunctionScaling("scaling.data") is throwing an error. 
Any help is appreciated.  
Using latest git update::: 
​---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-9-6b7978d71e71> in <module>
----> 1 m.setupSymmetryFunctionScaling("scaling.data")

pynnp.pyx in pynnp.Mode.setupSymmetryFunctionScaling()

RuntimeError: ERROR: Inconsistent scaling statistics.

**Comment by singraber** [comment]
Hmm.. unfortunately I cannot reproduce the error, in my case it finishes without any complaints.

The error message indicates that the symmetry function setup in `input.nn` is differing from the number of lines in the `scaling.data` file. Note, that whenever you make changes to the symmetry function setup (adding new ones, deleting some, or even just changing the parameters) you need to recalculate the statistics over the entire data set (use the tool `nnp-scaling`).

Can you make sure that you have not altered the files before running the example?

If there's still an error, maybe you can debug a little at the position where the error occurs.. this would be at `libnnp/SymmetryFunction.cpp` at lines 80-84.

**Comment by PrabhakarBhimalapuram** [comment]
it was a simple oversight on my part while handling files; the original example file "example-verbose.py" is working fine now. 
I apologize for the trouble.
