### ISSUE TITLE
training procedure

### ISSUE THREAD

**Issue by mhhfut** [CompPhysVienna/n2p2#20]
Thanks very much for sharing your code. I got some problems about the training procedure. Unfortunately, the document about the training procudure is incomplete. Hope you can give me some guide on the training procedure of n2p2.

**Comment by singraber** [comment]
Hey and sorry for the late reply... I will do my best to provide some more documentation in the next weeks. In the meantime, maybe this can get you started:

1. Prepare a data set (`input.data`) in the file format described [here](https://compphysvienna.github.io/n2p2/Topics/cfg_file.html). Unfortunately there's no simple recipe how to create a "good" set of configurations, you will find more hints in the literature. As a starting point you could try with some (100+) configurations taken from an _ab initio_ MD simulation.

2. Prepare a settings file (`input.nn`): Use the recommended file [here](https://github.com/CompPhysVienna/n2p2/blob/master/examples/input.nn.recommended) and change the settings in the "GENERAL NNP SETTINGS" section according to your system. Change the symmetry function definitions in the "SYMMETRY FUNCTIONS" section.. again this not a trivial task, have a look at these publications: [[1](http://doi.org/10.1063/1.3553717)], [[2](http://doi.org/10.1063/1.5024611)] and [[3](http://doi.org/10.1063/1.5019667)].

3. With the files `input.data` and `input.nn` ready in the same directoy, run the tool `nnp-scaling` (supports MPI parallelization). This will compute all symmetry functions for all atoms once and store statistics about them in a third file (`scaling.data`) required for training.

4. Run the actual training program `nnp-train`, preferably in parallel via:
   ```
   mpirun -np 16 nnp-train
   ```
   Be aware of the memory footprint which is estimated in the previous step (see end of log file or screen output).

5. Upon training weight files are created for each epoch `weights.???.<epoch>`. Select an epoch with satisfying RMSE and rename the corresponding weight files to `weights.???.data` (`???` is the atomic number of elements occurring).

6. Try the potential by predicting energies and forces for a new configuration: Collect the files from training (`input.nn`, `scaling.data` and `weights.???`) in a folder together with a single configuration (named again `input.data`) and run the tool `nnp-predict`. Alternatively, try to run a MD simulation with LAMMPS (see setup instructions [here](https://compphysvienna.github.io/n2p2/Topics/if_lammps.html) and [here](https://compphysvienna.github.io/n2p2/Topics/pair_nnp.html)).

Please also have a look at the `examples` directory which provides working example setups for each tool. If there are problems don't hesitate to ask again...

**Comment by mhhfut** [comment]
Appreciate for your detailed response. This helps me a lot. Thank you!
