### ISSUE TITLE
Charge/Partial Charge Caluclation

### ISSUE THREAD

**Issue by avikmahata** [CompPhysVienna/n2p2#33]
Is it possible to use fix qeq with N2P2? 

I am trying with an example of Water H2O with the same potential in the example directory. I tried with Fix qeq/fire it doesn't consider the charge, or it doesn't change the energy for some reason. I assume it will same for other qeq style also. 

Is there anyway I can use partial charge of each atoms in the simulation with N2P2? Do I have to consider charge per atom during the NN training?

**Comment by singraber** [comment]
I do not fully understand what you are trying to achieve here.. the provided water example does not make use of any charges, it is a short-range neural network potential. Hence, there is no dependence of the potential energy on the charges, so it is expected that `fix qeq` will not do anything.

Moreover, as of now n2p2 does not support NNPs with additional long-range part as described [here](http://dx.doi.org/10.1103/PhysRevB.83.153101).
