### ISSUE TITLE
Error in n2p2 compilation 

### ISSUE THREAD

**Issue by moabe75** [CompPhysVienna/n2p2#36]
Hi Everybody,

I'm trying to compile n2p2 package in my home directory on our HPC cluster. The most of the components have been compiled successfully. However, for the nnp-comp2, nnp-dataset, nnp-norm, nnp-scaling, and nnp-train components, I have faced an [error ](https://drive.google.com/open?id=1OnRFvZLeTVX8UOvLONciFzpXulLeFq1w) which is apparently related to the GSL libraries. I am using GSL 2.5, eigen 3.3.2,  and openmpi and gcc 4.0.1. It would be greatly appropriated if someone can help me to fix this issue. Many thanks.

**Comment by singraber** [comment]
Hello!
I am sorry, but I can not open the link with the error message, it asks me to create an account. Could you just copy the error here or attach a log file? Thanks!

**Comment by moabe75** [comment]
Sorry for that. Here it is:
[GSL_error.txt](https://github.com/CompPhysVienna/n2p2/files/4519314/GSL_error.txt)

**Comment by singraber** [comment]
It looks like the BLAS library on your HPC machine does not provide CBLAS symbols. Maybe it helps linking explicitly to the CBLAS library (`libcblas.so`). In `makefile.gnu` change https://github.com/CompPhysVienna/n2p2/blob/3759d96fd90e7239db691424b89f9676a782e216/src/makefile.gnu#L24
to
```
PROJECT_LDFLAGS_BLAS=-lblas -lcblas
```
Alternatively, try to switch to another BLAS library, like OpenBLAS or use ATLAS instead (With ATLAS try `PROJECT_LDFLAGS_BLAS=-llapack -lcblas -lf77blas -latlas`).

As a fallback you could also try to use the GSL-internal CBLAS implementation, just change the above line to
```
PROJECT_LDFLAGS_BLAS=-lblas -lgslcblas
```
Let me know if any of these options did work out!

**Comment by moabe75** [comment]
Hi Andreas,
Many thanks for your fast and helpful response. Finally, I've got it to work with ATLAS. Great. Now I need to ask you another question. I am trying to run some tests. I've started with calculating symmetry function values for H2O_RPBE-D3 example. However, it failed apparently agian due to the GSL. Could you have a look into this output file and see what the problem is. Thanks.
[slurm-12364488_error.txt](https://github.com/CompPhysVienna/n2p2/files/4522629/slurm-12364488_error.txt)

**Comment by moabe75** [comment]
Hi Andreas,
Many thanks for your fast and helpful response. Finally, I've got it to work with ATLAS. Great.
Now I am going to run some tests. Thanks again
