### ISSUE TITLE
Creating NNP from scratch

### ISSUE THREAD

**Issue by moabe75** [CompPhysVienna/n2p2#37]
Hi.
I've found out it's possible to create NNP from scratch using internal modules of the n2p2 package. I am going to try this for a small data set (100 data points of water) and use the trained NNP in the lammps simulations. 
What I think would be required is computing symmetry function values for the data set using "nnp-scaling" module and then training the NNP by "nnp-train" module. But, I am not entirely sure this procedure is correct. I would be greatly thankful if the n2p2 developer team can help me. Thanks.

**Comment by singraber** [comment]
I updated the docs with some information about the training procedure, see here: https://compphysvienna.github.io/n2p2/Topics/training.html
Hope this helps for the moment, more is about to be added, please stay tuned...

**Comment by moabe75** [comment]
Hi Andreas,

That is so great you have updated that part of the manual. Thank you.
I think it would be also helpful if you can add a part for computing "normalization factors" of data set using "nnp-norm" module.

**Comment by singraber** [comment]
Certainly, I will update the docs soon.. in the meantime I would like to direct you to the docs [here](https://compphysvienna.github.io/n2p2/Topics/units.html#normalizing-the-data-set-internal-units) and [this publication](https://doi.org/10.1021/acs.jctc.8b01092), where you can find in Chapter 3.1 details about the normalization procedure.

**Comment by singraber** [comment]
I added some documentation about the normalization.. about the tool [nnp-norm](https://compphysvienna.github.io/n2p2/Tools/nnp-norm.html) and the [training procedure](https://compphysvienna.github.io/n2p2/Topics/training.html#step-3-optional-data-set-normalization). Please have a look and tell me if something is still unclear! Thanks!

**Comment by moabe75** [comment]
Hi Andreas,
Many thanks for keeping the documentation updated and complete. I think this part is clear, helpful, and understandable. I just think it would be appropriated if you could add a few sentences regarding scaling the mean_energy with respect to the reference atom energies. Like what is the purpose of that, what should user do, etc and maybe noting that no matter whether the atomic reference energies are defined or not, the results of training or prediction should be the same. That is just a suggestion. 

Thanks again for such a great help and support.

Mostafa
