### ISSUE TITLE
Atom charge for short range NN

### ISSUE THREAD

**Issue by moabe75** [CompPhysVienna/n2p2#38]
Hi.

According to the manual, the atomic charges have to be introduced in the data file **only** for long-range NN training. I wonder for the short-range NN, would it be enough to set all atomic charges to zero in the data file or the corresponding column has to be removed completely? Many thanks.

Best,

**Comment by singraber** [comment]
The manual is a bit misleading here (I will edit this).. the long-range NN part is not (yet) implemented, so actually the charges are not used at all. You can safely set them to zero.

**Comment by moabe75** [comment]
Thank you for your clarification.
