### ISSUE TITLE
Free atom reference energies in Lammps interface

### ISSUE THREAD

**Issue by moabe75** [CompPhysVienna/n2p2#41]
Hi.
I've got a question regarding the "input.nn" file in the lammps interface. In the water example, the free atom reference energies are commented. Why don't we need them for the lammps simulations?
I've found out this leads to predicting wrong potential energies in the simulations.  I got the correct energies by removing # from the corresponding lines. Thanks.

**Comment by singraber** [comment]
Hey!

How do you know that the energies are wrong if you use the given example? When I run LAMMPS I find that the initial configuration has the potential energy `-6000558.1 eV` which corresponds to approximately `-694.5 eV` per atom. This is very close to the per-atom-energies in the data set taken from [here](https://compphysvienna.github.io/n2p2/index.html#training-data-sets-full-size) (note the different units). So I think the prediction does not need any additional offset energies.

Regarding the atomic reference energies in the settings file: If the data set normalization is used (presence of keywords `mean_energy`, `conv_energy` and `conv_length`... more information coming up in the docs, in the meantime have a look [here](https://compphysvienna.github.io/n2p2/Topics/units.html#normalizing-the-data-set-internal-units)), the `atom_energy` keyword is usually not used. The reference energy (`atom_energy`) is absorbed in the `mean_energy` value.

**Comment by moabe75** [comment]
Many thanks Andreas for the clarification. Actually the problem I got was in my own water example. Sorry for the misleading in my previous massage. The examples in the package work very well. 
I've just found out the problem is in my "norm" calculation. Definitely the mean energy is not correct. I used the input.nn file from the "examples\nnp-norm\H2O_RPBE-D3". Here is the output file:
[output.nn.txt](https://github.com/CompPhysVienna/n2p2/files/4570642/output.nn.txt)
I guess something is wrong in the data file:
[input.data.txt](https://github.com/CompPhysVienna/n2p2/files/4570644/input.data.txt)

Could you please have a look into that.

**Comment by moabe75** [comment]
Can not be due to the inconsistency between the total potential energy in the data file and the free atomic energies? I did AIMD under PBC for this data set. In my case the energy of each water is around -34 Hartree (-551/16), while in your case (H2O_RPBE-D3) is around -76.5 (-1225/16) in consistence with the free atom reference energies of O and H.

**Comment by moabe75** [comment]
What happens if I compute the normalization factors without providing the free atomic reference energies?
