### ISSUE TITLE
lammps rigid body simulations

### ISSUE THREAD

**Issue by moabe75** [CompPhysVienna/n2p2#44]
Hi Andreas,

I'm going to run rigid body simulations for a solute+solvent systems. What I am trying to do is running the simulations by keeping the solute fixed in middle of box while all solvent molecules are flexible. To do so, I should group all atoms, for example to the solute and solvent groups by their atom types. However, this way leads to an inconsistency between the number of LAMMPS atom types and the NNP elements. I've been thinking maybe I should try pair_style hybrid and using the same nnp for both groups, but I have no idea how the lammps input file should look like. The following is an example: my solute in 17 solvent molecules. I appropriate if you can help me. 

[lmp_input.txt](https://github.com/CompPhysVienna/n2p2/files/4623369/lmp_input.txt)
[data_file.txt](https://github.com/CompPhysVienna/n2p2/files/4623323/data_file.txt)

**Comment by singraber** [comment]
Hey,

I think a similar issue came up when discussing the use of `pair_style hybrid` here: #29. The solution there is an extra keyword `emap` which may do the trick for you too.. you can select which atom types are actually handled by the NNP and which are ignored. Note that I have not yet merged the branch #30 yet so you need to check out the specific branch for trying it out.

Also, I have not tested what happens if you only apply the NNP to a group of atoms, does this work in principle for you?

**Comment by moabe75** [comment]
I have tried that for this example:
I have one group for the solute atom (type 1, 2, 3, 4, and 16) and another group for the solvent atoms (type 5, 6, 7, 8,9 ,10 ,11 ,12 ,13 ,14 ,15 ,17 ,18 ,19 , and 20). For the case that I want to apply NNP to the both groups, I think it should be like this:

pair_style hybrid/overlay nnp dir ${nnpDir} emap "1:H,2:H,3:H,4:H,16:C" showew no showewsum 1000 resetew yes maxew 1000 cflength 1.8897261328 cfenergy 0.0367493254 nnp dir ${nnpDir} emap "5:H,6:H,7:H,8:H,9:H,10:H,11:H,12:H,13:H,14:H,15:H,17:C,18:C,19:C,20:C" showew no showewsum 1000 resetew yes maxew 1000 cflength 1.8897261328 cfenergy 0.0367493254

pair_coeff * * nnp ${nnpCutoff}

However, it does not work: "ERROR: Pair coeff for hybrid has invalid style (../pair_hybrid_overlay.cpp:65)". Do I need to introduce explicitly all atomic pairs in the pair_coeff command for both groups?  

Note that I have tried this with the "n2p2-fix_lammps_hybrid" version.

**Comment by singraber** [comment]
I am not sure whether this is the reason for the error but the `emap` argument is a list of atom **types** to elements, not atom indices!

**Comment by moabe75** [comment]
These are actually the atom types. So 5 atom types for CH4 solvent molecule and 15 for my vdW complex. If I want to simplify it, it would be like this:

pair_style hybrid/overlay nnp dir ${nnpDir} emap "1:H,2:C" showew no showewsum 1000 resetew yes maxew 1000 cflength 1.8897261328 cfenergy 0.0367493254 nnp dir ${nnpDir} emap "3:H,4:C" showew no showewsum 1000 resetew yes maxew 1000 cflength 1.8897261328 cfenergy 0.0367493254

pair_coeff * * nnp ${nnpCutoff}

atom types 1 and 2 for the solvent and 3 and 4 for the solute. I also tried this, but got the same error. Could you please, if you get any time, have a look into this? Many thanks.

[md.lmp.txt](https://github.com/CompPhysVienna/n2p2/files/4624386/md.lmp.txt)
[system.data.txt](https://github.com/CompPhysVienna/n2p2/files/4624387/system.data.txt)
