### ISSUE TITLE
Energy and forces prediction

### ISSUE THREAD

**Issue by moabe75** [CompPhysVienna/n2p2#46]
Hi Andreas,
I wonder how I can predict the energy and forces for a bunch of structures by a single run of the "nnp-predict" module. I tried that, but it seems it doesn't go through all structures in the "input.data" file and it only takes the first one.

**Comment by singraber** [comment]
Hey,
there is another tool for exactly that purpose which is called `nnp-dataset`. Unlike `nnp-predict` it supports MPI parallelization.. hence you can distribute the computation for a large dataset to multiple cores, e.g. run on 16 cores:
```
mpirun -np 16 nnp-dataset 0
```
There is one command line argument (allowed values are `0` or `1`) which turns on or off random distribution to MPI cores (better load-balancing but you get a different ordering in the output files).

The tool creates not the same output files as `nnp-predict`. Instead, you get `energy.comp` and `forces.comp` which contain a side-by-side comparison of reference and predicted energies/forces. There is even more output.. I will add some documentation soon.. hope this helps for the moment!

**Comment by moabe75** [comment]
Many thanks Andreas. That is exactly what I want. 

Mostafa
