### ISSUE TITLE
Discrepancy in energy predictions and CP2K calculations

### ISSUE THREAD

**Issue by fireballpoint1** [CompPhysVienna/n2p2#47]
**The question**
I am running an NVT simulation in LAMMPS using n2p2 and then ran CP2K calculations on the trajectory. The energy values from N2P2 stdout is roughly 27.4x the CP2K calculation. I am not sure about the places to look into for the same

**Comment by singraber** [comment]
Sorry I was not able to answer your question at the time...

Next time please add some more details.. it's impossible to answer this question without more information
