### ISSUE TITLE
nnp-sacling wrong output order

### ISSUE THREAD

**Issue by marian-code** [CompPhysVienna/n2p2#50]
Hi, I noticed that nnp-scaling outputs symmetry function values to `function.data` file in random order when MPI parallelization is used.
This does not happen if nnp-scaling runs in serial mode

**Comment by singraber** [comment]
Hey,

sorry for the delay... hmm, that is of course not the desired behavior, I will have a look at this! Thanks for reporting!

**Comment by singraber** [comment]
I am sorry, but I can not reproduce this. I get identical `function.data` files, no matter what number of cores I select. Looking into the source code this is also what I expect, see:
https://github.com/CompPhysVienna/n2p2/blob/6c59866a54ef87e46714eb441294c699a07d7c65/src/libnnptrain/Dataset.cpp#L1093-L1099
Maybe there is a more delicate bug behind this, can you send me a minimum working example?
