### ISSUE TITLE
Problem with different atomic neural network architectures in NNP 

### ISSUE THREAD

**Issue by AleaTokita** [CompPhysVienna/n2p2#51]
Hello, I have a problem using different atomic neural network architectures for the individual elements in my NNP.  When I am trying to run a MD simulation using this NNP, n2p2 seems to build the same atomic neural network architectures for all elements. There is no error message but of course the NNP constructed by n2p2 is unable to describe the given structure since the weights belong to a different architecture. 

Here is a small example:
[n2p2_architecture_problem.zip](https://github.com/CompPhysVienna/n2p2/files/4798965/n2p2_architecture_problem.zip)

**Comment by singraber** [comment]
Thanks for reporting this and for providing an example... I wrote a fix which solves the problem for me (see #52). I have already merged this with the main repository. Please try it out and report back if it works for you too!

Note, that this only implements the keyword `element_nodes_short`, but not the related `element_hidden_layers_short` nor `element_activation_short`.

**Comment by AleaTokita** [comment]
Many thanks for writing the fix, I will test it and report back as soon as possible (I am just a little busy at the moment).
