### ISSUE TITLE
Finding similar data points

### ISSUE THREAD

**Issue by moabe75** [CompPhysVienna/n2p2#58]
Hi.

I have a big data set. I wonder if there is a way in n2p2 to find/determine (very)similar data points, which enables me to remove redundant structures. Thanks.

**Comment by singraber** [comment]
Hello,

do you mean to eliminate real duplicates or to find configurations which are similar in energy, forces and typical atomic environment?

For the latter there is a still open PR #13 by Alexander Kaiser who implemented farthest point sampling.. I will have a look right now whether I can actually merge this right away...

**Comment by moabe75** [comment]
Hi Andreas,
Yeah, those configurations which are similar in energy, forces and typical atomic environment. 
I would greatly appropriate it if you could get it done today. Many thanks.

**Comment by singraber** [comment]
I have just brought the PR up to date and integrated the new tool `nnp-fps` in the current build process... I am not yet happy with the output and that there is no parallelization, so I will not yet merge with the master. Anyway, in the meantime you can try out this tool by checking out the Alexander Kaisers repository:

```
git clone git@github.com:AKaiser85/n2p2.git n2p2-AKaiser85
```
If you try it please report back whether it is working for you or where you found problems... many thanks!

**Comment by singraber** [comment]
A precursor of a useful documentation can be found here: https://github.com/AKaiser85/n2p2/blob/master/src/doc/sphinx/source/Tools/nnp-fps.rst

**Comment by moabe75** [comment]
Many thanks. I will give it try and report back the results.

**Comment by singraber** [comment]
I have some doubts about how the farthest point sampling is implemented in #13... have a look at my comments there. Maybe you can have a look too whether the construction of the `allG` vector makes sense for you?

**Comment by moabe75** [comment]
I see. I will check that out too.
