### ISSUE TITLE
Automatic selection of fingerprints

### ISSUE THREAD

**Issue by psn417** [CompPhysVienna/n2p2#63]
Hello!

One of your papers introduces the automatic selection of fingerprints. It seems useful. How can I use these methods in n2p2 training procedure? Have you implemented automatic selection in your program?

**Comment by singraber** [comment]
Hi!

Indeed, there is the tool `nnp-prune` (see [docs](https://compphysvienna.github.io/n2p2/Tools/nnp-prune.html)) which allows some basic fingerprint selection. However, the two procedures offered are not very sophisticated. The `range` mode must be performed in between step 4 and 5 of [this training scheme](https://compphysvienna.github.io/n2p2/Topics/training.html) while the `sensitivity` procedure can only be performed after training and requires retraining afterwards.

If you want to play around with fingerprint selection by yourself in python you can try the `pynnp` python interface and use [this example](https://github.com/CompPhysVienna/n2p2/blob/master/examples/pynnp/symfunc-only/example.py) as a basis.
