### ISSUE TITLE
New release of n2p2

### ISSUE THREAD

**Issue by moabe75** [CompPhysVienna/n2p2#66]
Hi Andreas,
Today, I've updated my n2p2 package to the latest version 2.0.1. However, in the output files it still prints "NNP LIBRARY v2.0.0". I double checked everything and I am pretty sure that I am using the newest release (2.0.1). I wonder what and where the problem is.

Thanks,
Mostafa

**Comment by singraber** [comment]
Hi,
no need to worry, this is just because I forgot to update the actual version number in the header file, sorry for this. I have to get used to do proper version numbers on a regular basis.
Best,
Andi
