### ISSUE TITLE
Different results from different epochs

### ISSUE THREAD

**Issue by moabe75** [CompPhysVienna/n2p2#69]
Hi Andreas,
I've facing a problem with using the trained NNP for the ML MD simulations. I get different results in the MD simulations when I use different epochs that have very similar force and energy RMSEs. For example, in the following case, epochs 28 and 30 predict different mass densities in the MD simulations.
I need to know what and where is the source of this issue. Does it show that the fitting procedure is not converged properly and probably more epoch is needed? If so, how can I make sure that enough numbers of epochs are used?
In this example, I used 0.006 for the short_force_fraction. Can't it be due to this. 
Note that the data set is constructed through several AIMD simulations at 8 different temperatures. I appropriate your help. 

epoch RMSEpa_Etrain_pu  RMSEpa_Etest_pu   RMSE_Ftrain_pu    RMSE_Ftest_pu   RMSE_Etrain_pu    RMSE_Etest_pu
   0   3.68089707E-03   3.68151650E-03   3.59133943E-02   3.57132410E-02   2.20853824E-01   2.20890990E-01 
   1   7.52728841E-05   7.53545746E-05   4.70025592E-03   4.69005246E-03   4.51637304E-03   4.52127448E-03 
   2   5.88296966E-05   5.83460717E-05   4.43031439E-03   4.41829441E-03   3.52978180E-03   3.50076430E-03 
   3   4.15278857E-05   4.25868378E-05   4.31353267E-03   4.30069945E-03   2.49167314E-03   2.55521027E-03 
   4   3.46008856E-05   3.52571984E-05   4.28745565E-03   4.27184553E-03   2.07605314E-03   2.11543190E-03 
   5   3.65203293E-05   3.69307190E-05   4.28136598E-03   4.26524519E-03   2.19121976E-03   2.21584314E-03 
   6   3.10717952E-05   3.17880035E-05   4.26292456E-03   4.24489046E-03   1.86430771E-03   1.90728021E-03 
   7   2.88128049E-05   2.95575016E-05   4.27352932E-03   4.25524627E-03   1.72876829E-03   1.77345010E-03 
   8   2.85200475E-05   2.91802980E-05   4.26418055E-03   4.24542472E-03   1.71120285E-03   1.75081788E-03 
   9   3.09585962E-05   3.17343691E-05   4.26567502E-03   4.24609761E-03   1.85751577E-03   1.90406215E-03 
  10   2.85033317E-05   2.92720727E-05   4.27303803E-03   4.25317515E-03   1.71019990E-03   1.75632436E-03 
  11   3.00620617E-05   3.06763090E-05   4.26079157E-03   4.24176376E-03   1.80372370E-03   1.84057854E-03 
  12   2.95305319E-05   3.00977848E-05   4.25870712E-03   4.23950932E-03   1.77183192E-03   1.80586709E-03 
  13   2.84858645E-05   2.91128325E-05   4.26058927E-03   4.24188254E-03   1.70915187E-03   1.74676995E-03 
  14   2.87682309E-05   2.93136446E-05   4.27371320E-03   4.25604482E-03   1.72609385E-03   1.75881868E-03 
  15   2.82961184E-05   2.88206081E-05   4.26244979E-03   4.24451240E-03   1.69776710E-03   1.72923649E-03 
  16   3.84394897E-05   3.86483941E-05   4.26675450E-03   4.24832075E-03   2.30636938E-03   2.31890365E-03 
  17   2.93523727E-05   2.96756732E-05   4.26840025E-03   4.24889049E-03   1.76114236E-03   1.78054039E-03 
  18   2.71961406E-05   2.76404737E-05   4.26227084E-03   4.24309386E-03   1.63176844E-03   1.65842842E-03 
  19   3.24900849E-05   3.28368894E-05   4.25682390E-03   4.23786426E-03   1.94940509E-03   1.97021336E-03 
  20   2.84659028E-05   2.86453038E-05   4.27959344E-03   4.26016810E-03   1.70795417E-03   1.71871823E-03 
  21   2.75537644E-05   2.82404578E-05   4.25843586E-03   4.23903460E-03   1.65322587E-03   1.69442747E-03 
  22   2.94481195E-05   2.99895730E-05   4.26189698E-03   4.24209250E-03   1.76688717E-03   1.79937438E-03 
  23   3.05071253E-05   3.09408362E-05   4.25319316E-03   4.23364649E-03   1.83042752E-03   1.85645017E-03 
  24   2.83537714E-05   2.86469758E-05   4.26034088E-03   4.24039826E-03   1.70122628E-03   1.71881855E-03 
  25   2.66472039E-05   2.71158073E-05   4.25740052E-03   4.23840281E-03   1.59883223E-03   1.62694844E-03 
  26   3.26086533E-05   3.30212435E-05   4.26373495E-03   4.24495621E-03   1.95651920E-03   1.98127461E-03 
  27   2.97659954E-05   3.01094481E-05   4.26098456E-03   4.24175193E-03   1.78595972E-03   1.80656688E-03 
  **28   2.61664264E-05   2.65340505E-05   4.26240041E-03   4.24326213E-03   1.56998558E-03   1.59204303E-03** 
  29   3.05201863E-05   3.08942275E-05   4.25136483E-03   4.23223061E-03   1.83121118E-03   1.85365365E-03 
  **30   2.99563143E-05   3.03292610E-05   4.25421462E-03   4.23467312E-03   1.79737886E-03   1.81975566E-03** 

Many thanks.
Mostafa

**Comment by singraber** [comment]
Hi Mostafa,

unfortunately I can't tell what is going on here without actually knowing more about your system... I can only ask you to check some things:

* What are the RMSEs of energies and forces in eV/atom and eV/Angstrom, respectively (i.e. which units are shown in your message)?
* Have you looked whether the comparison in `trainpoints.???...` and `trainforces.???...` for these epochs look reasonable?
* How can you know that the different densities you get from the MD simulation are not within errors bars?
* And if they are VERY different have you looked at the trajectories?
* Can you also check whether the extrapolation warnings during the MD runs show something unexpected (e.g. a sudden increase)?

Best,
Andreas

**Comment by moabe75** [comment]
Hi Andreas,
Thank you very much for your suggestions. If I'm not mistaken, the units for the energy and forces RMSEs are Hartree and Hartree/Bohr (physical units in n2p2). I just copied them directly from the "learning-curve.out" file. 
Regarding the point 5, no extrapolation warning is observed during the ML MD simulations. I think your points 3 and 4 can be responsible for this issue. I will check them out.  

Best,
Mostafa

**Comment by moabe75** [comment]
Hi Andreas,
Thank you very much for your suggestions. If I'm not mistaken, the units for the energy and forces RMSEs are Hartree and Hartree/Bohr (physical units in n2p2). I just copied them directly from the "learning-curve.out" file. 
Regarding the point 5, no extrapolation warning is observed during the ML MD simulations. I think your points 3 and 4 can be responsible for this issue. I will check them out.  

Best,
Mostafa
