### ISSUE TITLE
Error (?) in documentation of lammps interface usage

### ISSUE THREAD

**Issue by mastricker** [CompPhysVienna/n2p2#7]
Hi,
not sure if this came with the newest lammps version (as of January 4th), but something I noticed:

**Double line definition of `pair_style nnp` is not corrected in documentation**
In [pair_style doc](https://compphysvienna.github.io/n2p2/pair_nnp.html), the suggested usage of the nnp package as a potential is listed like this:
```
pair_style nnp showew yes showewsum 100 maxew 1000 resetew yes cflength 1.8897261328 cfenergy 0.0367493254
pair_style nnp dir "./" showewsum 10000
pair_coeff * * 6.01 
```
But when copying this exactly into a lammps configuration file, the keywords of the first line are overwritten (i.e. set to default), when the second line is read. This e.g. leads to conversion factors with are `1.0`.
By defining it in one line, it works:
```
pair_style nnp showew yes showewsum 100 maxew 1000 resetew yes cflength 1.8897261328 cfenergy 0.0367493254 dir "./" showewsum 10000
pair_coeff * * 6.01 
```
Not sure if something in lammps changed or if I need to do something extra, but just compiling lammps including the nnp package has this behaviour.

**To Reproduce**
1. n2p2 v1.0.0, lammps patch_4Jan2019
2. gnu compiler suite, n2p2: `make libnnpif-shared`, copy user package to lammps, lammps: `make yes-user-nnp && make mpi`

**Expected behavior**
No overwriting of previously defined values of keywords

Thanks!
Markus

**Comment by singraber** [comment]
Hi Markus,

thanks for noticing and for taking the time to file the issue!

I'm sorry this caused some confusion.. I tried to stick very close the LAMMPS documentation format, where the examples section usually contains multiple lines which are actually not intended for direct use but rather as a collection of possible argument combinations (see e.g. https://lammps.sandia.gov/doc/pair_cs.html). Anyway, to avoid future confusion I included a warning in the new docs:

https://compphysvienna.github.io/n2p2/Topics/pair_nnp.html

All the best,

Andi
