### ISSUE TITLE
scale_symmetry_functions

### ISSUE THREAD

**Issue by AmAuryCte** [CompPhysVienna/n2p2#71]
Hello, 

I have an issue with the scaling procedure of symmetry functions. I set Smin and Smax to -1 and 1 respectively as it is written above. However in the nnp-scaling.log it is written "No scaling for symmetry functions".

Best regards,

Amaury

scale_symmetry_functions                       # Scale all symmetry functions with min/max values.
scale_min_short                 -1.0            # Minimum value for scaling.
scale_max_short                 1.0            # Maximum value for scaling.

**Comment by singraber** [comment]
Hi,

this is normal.. the scaling data (in the file `scaling.data`) will be produced by the tool nnp-scaling. Hence, when the tool is running there is nothing to scale yet and the n2p2 core library (`libnnp`) shows this message. When you continue with other tools (e.g. `nnp-train`) the scaling information should be correctly displayed.

Best,

Andreas
