### ISSUE TITLE
where are the atoms giving EW

### ISSUE THREAD

**Issue by hyharry** [CompPhysVienna/n2p2#76]
Hi n2p2 developers, 

I am doing relaxation for a large atom system (about 1MIo atoms). It works fine for most of the time, even when I start with some slightly unphysical system. Namely, at the beginning the relaxation throws some EW (extrapolation warnings). With the simulation going, the relaxation can pull the system back to normal state (no EW any more). I am using a mix of minimization method (cg and fire in lammps).

However, for one case, the system is fine at the beginning, then starts to give a lot of EW and then fail with too many EW. To understand why this happens, I would like to check where are these atoms throwing EW. Then I can tell whether the system is physical in that region or not (too many close atoms? or some configurations that I did not sample in my training data sets). 

So I would like to know whether the following is possible,
1. output the atom id for EW
2. what types of symfunc that gives this EW, radial or angular, what is the index of symfunc

I have checked the documentation. The showew option can tell some information, somehow it is not very detailed. 

Thanks for helping!

**Comment by singraber** [comment]
Hello!

Yes, this information will be printed to screen and to the LAMMPS log file when you set `showew yes`. I just pushed a [commit](https://github.com/CompPhysVienna/n2p2/commit/bac02c30ecf8c29459c2aa20b06a7069ea8c60c9) that improves this feature a little bit to make it more verbose, so please check out the latest version. It will now print a line for each extrapolation warning like this
```
### NNP EXTRAPOLATION WARNING ### STRUCTURE:      0 ATOM:       119 ELEMENT: Cu SYMFUNC:   32 TYPE:  3 VALUE:  2.166E-02 MIN:  2.003E-05 MAX:  1.756E-02
```
 with the following fields:

`STRUCTURE` : The LAMMPS interface prints here the MPI rank where the atom which triggered the EW resides.
`ATOM` : This is the internal LAMMPS tag, i.e. the global atom index of LAMMPS.
`ELEMENT` : The element string of the atom (which is equal to the element of the symmetry function).
`SYMFUNC` : Index of the symmetry function (corresponds to the index given in the log file).
`TYPE` : The symmetry function type encoded as integer number (resolve [here](https://compphysvienna.github.io/n2p2/topics/keywords.html#symfunction-short))
`VALUE` : Symmetry function value which triggered the EW check.
`MIN` and `MAX` : The symmetry function boundaries as set by the `scaling.data` file.

It should be possible to identify the problematic region with the `ATOM` index.. if it is possible for you to visualize the trajectories (e.g. with VMD) you can use this number to select only this atom and its environment. (I am not sure whether LAMMPS tags start with 0 or 1, so you may have to add +/-1 to the index).

Hope this helps!

Best,

Andreas

**Comment by hyharry** [comment]
Great! Thanks for helping.
best wishes,
Yi

**Comment by vsumaria** [comment]
Is there a way this could be implemented within pynnp method? Basically such that any random structure that is read, we can find if the structure is in the interpolation or the extrapolation region? (such that it can added back to training if required)

**Comment by singraber** [comment]
Sorry, there is no feature for this in `pynnp` but you could use the C++ tool `nnp-comp2` which is designed for the purpose to find untrained (or not well trained) configurations in a given data set. There is no doc page yet but please have a look at this post:

https://github.com/CompPhysVienna/n2p2/issues/62#issuecomment-688379042

You basically need an `input.data` with the structures of interest and two already trained NNP instances for comparison.
