### ISSUE TITLE
Restarting the training process

### ISSUE THREAD

**Issue by moabe75** [CompPhysVienna/n2p2#78]
Hi Andreas,
Is it possible to restart the training procedure from a fitted nnp model in n2p2? I want to see if more epochs can improve the quality of the model.

Thanks,
Mostafa

**Comment by singraber** [comment]
Hi,

yes this is possible by using the keyword `use_old_weights_short` in the `input.nn` file.

Best,
Andreas

**Comment by moabe75** [comment]
Many thanks Andreas. That is very helpful. 

Best,
Mostafa
