### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by jduerholt** [CompPhysVienna/n2p2#8]
Hi,
I did not found in the documentation any information about the units used in the package. Can you tell me which units are used for distances, energies and forces, or point me to the page where it is mentioned in the documentation?
Best
Johannes

**Comment by singraber** [comment]
Hi Johannes,

sorry for the late reply..

There are no specific units assumed by any of the tools, i.e. whatever unit system you use for training, will determine which units are later required for prediction. For example, if you used Angstrom/eV for lengths/energies during training you need to stick to these units later on. I added some information about this topic to the documentation, see here:

https://compphysvienna.github.io/n2p2/Topics/units.html

If your question refers to the existing potentials given in the `examples/potentials` directory, the unit systems used during training are:

- H2O_*: Bohr / Hartree
- CuS2_PBE : Angstrom / eV

Hope this helps a bit..

All the best,

Andi
