### ISSUE TITLE
Building CabanaMD interface

### ISSUE THREAD

**Issue by moabe75** [CompPhysVienna/n2p2#82]
Hi Andreas,
I am trying to build the CabanaMD interface. I am getting this error message: 
[error_message.txt](https://github.com/CompPhysVienna/n2p2/files/5906918/error_message.txt)

It seems, it's related to the n2p2 part. Could you please have a look into this and see if you can help me to fix it. 

Many thanks.

Mostafa

**Comment by singraber** [comment]
Hi,

please try again with version 2.0.1 of n2p2 (`git checkout v2.0.1` or https://github.com/CompPhysVienna/n2p2/releases/tag/v2.0.1) at the moment. There were quite some changes in the latest v2.1.0 or the `master` branch and I don't have the time right now to test whether they broke the CabanaMD interface.

Best,
Andi

**Comment by moabe75** [comment]
Hi Andi,
I think it's working with this version of n2p2. It's compiled successfully. I only got another problem with the CabanaMD. Once it's fixed, I'll try to run some tests. Many thanks.  

Best,
Mostafa

**Comment by moabe75** [comment]
Hi Andreas,
Finally, I could get the CabanaMD/n2p2 interface to work. It works for the nnp example, but when I tried it for my system first it complained about the most of keywords in the input file, like "boundary", and at the end it turned out that it only works for the NVE simulations. Have you ever tried it? Is it really limited to the nve simulations?

Best,
Mostafa

**Comment by singraber** [comment]
Hi,

Yes, I have tried the given example and I am aware that CabanaMD does not have all features of LAMMPS, it is obviously under heavy development.. please contact the developers for more information about existing and future features.

Best,
Andi

**Comment by moabe75** [comment]
Many thanks Andi. I'll ask them.

Mostafa
