### ISSUE TITLE
Understanding the "short_force_error_threshold" keyword

### ISSUE THREAD

**Issue by moabe75** [CompPhysVienna/n2p2#83]
Hi Andreas,

I'm trying to understand the role of the "short_force_error_threshold" (or "short_energy_error_threshold") keyword. As I realized from the manual, when, for instance, a value of 0.1 is specified, a threshold of 0.1*force RMSE is set and if the **error** is above this threshold then the training forces candidates are updated/selected randomly for the weight update. This means, the smaller value is selected for the keyword, the more frequent the forces will be used for the weight update. If I've understood it correctly, I need to know what the **error** is. Is it the mean absolute error (MAE) of forces? 
Thanks.

Mostafa

**Comment by singraber** [comment]
Hi,

it works as follows: as with `selection_mode 0` energies/forces are selected randomly from the training set but BEFORE they are actually used to update the weights they have to pass an additional test: the energy/force is computed using the current weights and the absolute error is compared to the global RMSE of the last epoch:

```
                        currentRmseFraction.at(b) =
                            fabs(s.energyRef - s.energy)
                            / (s.numAtoms * pu.errorTrain.at("RMSEpa"));

1. Select

**Comment by moabe75** [comment]
Many thanks for your thorough explanation. That helps a lot.

Mostafa

**Comment by moabe75** [comment]
Hi Andreas,
I've got a question. Do you think it would be worth to try different values for the "short_force_error_threshold" in order to find an optimal value for a better fit. For example, trying three 0.1, 0.5, and 1.0 values for that same NN architecture and same random seed and then evaluate them by comparing the results of the ML MD simulations. I'm thinking to use this parameter to control the quality of the fit.  Do you think it is a good idea?

Thanks,
Mostafa
