### ISSUE TITLE
Relation between "force_weight" and "short_force_fraction"

### ISSUE THREAD

**Issue by moabe75** [CompPhysVienna/n2p2#86]
Hi Andreas,
Previously, in order to improve the force RMSE, you suggested to play with the "short_force_fraction" keyword. If I set a value for this keyword so that a 1:10 ratio between energy and force updates is obtained, do I need to specify 10 for "force_weight". From the definition it seems there is a relation between these two keywords. I would be thankful if you have a comment on this. Many thanks.

Best,
Mostafa

**Comment by singraber** [comment]
Hi,

no these two keywords are not "interacting", they do have a different definition: one controls **how many** forces are used per update, the other influences how forces are **weighed** w.r.t. energies. I already commented this here: https://github.com/CompPhysVienna/n2p2/issues/67#issuecomment-723226588 , please be more specific if this is still unclear to you.

Best,
Andreas
