### ISSUE TITLE
How do I use fitted NN potential from RuNNer in lammps using n2p2? 

### ISSUE THREAD

**Issue by abhirup86** [CompPhysVienna/n2p2#87]
Hello,

I have NN potential from RuNNer code, however, I am not sure how to use that for lammps simulation. I tried to use n2p2 package by building lammps using "make" inside n2p2/src/interface/LAMMPS which build lmp_mpi inside lammps-nnp. I can successfully run dynamics using this lmp_mpi in serial mode for the examples (Cu2S and H2O), but, I cannot run it using mpirun (Not sure why). However, when I use the same lmp_mpi using the weights, and all other files from the RuNNer it throws the error message "cutoff_type" not found. When I set a cutoff_type inside input.nn, it runs but crashes with an error message- terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR: LAMMPS cutoff via pair_coeff keyword is smaller than maximum symmetry function cutoff.

Can you please help me with it how to use LAMMPS using RuNNer/N2P2?

**Comment by singraber** [comment]
Hi!

I'm afraid I do not understand what happened regarding the MPI problem: there is no makefile in ``n2p2/src/interface/LAMMPS``, I guess you mean ``n2p2/src/interface``. Please follow the instructions given in the [automatic build section](https://compphysvienna.github.io/n2p2/interfaces/if_lammps.html#automatic-build) of the docs. How do you know that the parallel run doesn't work, what is the error?

``cutoff_type`` is a mandatory keyword, I was not aware that it is optional in RuNNer. If you don't include it in ``input.nn``, what's then the default taken by RuNNer? Is there another keyword used to determine the cutoff function type?

Please read carefully the [pair_style nnp](https://compphysvienna.github.io/n2p2/interfaces/pair_nnp.html) documentation as it tells you how to set the ``pair_coeff`` arguments. You have to use the largest cutoff occurring in your symmetry function setup BUT make sure that in the LAMMPS script you use the correct length units (those of LAMMPS, NOT the ones used in training). If you use different units for your MD run than you did use for training with RuNNer, you have to use the ``cfenergy`` and ``cflength`` keywords.

**Comment by abhirup86** [comment]
Hi,

Thanks for the quick response. 

1 Error when I run "mpirun -np 4 ./lmp_mpi -in md.lmp" 
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR: LAMMPS cutoff via pair_coeff keyword is smaller than maximum symmetry function cutoff.

Here is my md.lmp
###############################################################################
# MD simulation for NN Ru N2 first data from input.data
###############################################################################

###############################################################################
# VARIABLES
###############################################################################
clear
# Configuration files
variable cfgFile         string "Ru_n2.data"
# Timesteps
variable numSteps        equal  100
variable dt              equal  0.001
# NN
variable nnpCutoff       equal  6.01
variable nnpDir          string "nnp-data"
# Masses
variable mass_Ru          equal  101.07                                                  # mass for element 1 (S)  (g/mol)
variable mass_N           equal  14.0067                                                 # mass for element 2 (Cu) (g/mol)

###############################################################################
# GENERAL SETUP
###############################################################################
units metal
boundary p p p
atom_style atomic
read_data ${cfgFile}
mass 1 ${mass_Ru}
mass 2 ${mass_N}
timestep ${dt}
thermo 10

###############################################################################
# NN
###############################################################################
pair_style nnp dir ${nnpDir} showew no showewsum 100 resetew no maxew 100 cflength 1.0 cfenergy 1.0 emap "1:Ru,2:N"
pair_coeff * * ${nnpCutoff}
###############################################################################

# INTEGRATOR
###############################################################################
fix INT all nve
dump 1 all atom 10 traj.dump

2 Yes, cutoff_type was not set in input.nn used in RuNNer to fit the potential. Is that mean I have to fit the potential via n2p2 not RuNNer or I should re-fit it in RuNNer adding cutoff_type. 

Here is the input.nn for the fitting in RuNNer 

### #############################################################
### This is the input file for RuNNer (version 0_44 and upwards)
### #############################################################
### General remarks: 
### - commands can be switched off by using the # character at the BEGINNING of the line
### - the input file can be structured by blank lines and comment lines
### - the order of the keywords is arbitrary
### - if keywords are missing, default values will be used and written to runner.out
### - if mandatory keywords or keyword options are missing, RuNNer will stop with an error message 

#initialization_only
########################################################################################################################
### general keywords
########################################################################################################################
nn_type_short 1                           # 1=Behler-Parrinello, 2=Pair NN
runner_mode 3
parallel_mode 1                           # parallelization mode                                 (not fully implemented yet)
number_of_elements 2                      # number of elements                                   (nelem)                       MODE1+2+3+4
elements Ru N                             # specification of elements                            (element)                     MODE1+2+3+4
random_seed 20                            # seed for initial random weight parameters and train/test splitting (iseed)         MODE1+2
random_number_type 5                      # 1=ran0, 2=ran1, 3=ran2, 4=ran3
#atom_energy Ru -0.088261                 # free atom reference energy (atomic zora)
#atom_energy N  -0.116525                 # free atom reference energy (atomic zora)
energy_threshold -0.291                   # energythreshold for fitting data in Ha per atom      (fitethres)                   MODE1
bond_threshold 1.1d0                      # threshold for the shortest bond in structure         (rmin)                        MODE1+2+3

########################################################################################################################
### NN structure of the short-range NN  
########################################################################################################################
use_short_nn                              # use NN for short range interactions                  (lshort) 
global_hidden_layers_short 2              # number of hidden layers                              (num_layersshort-1)
global_nodes_short 20 20                  # number of nodes in hidden layers                     (nodes_short)
global_activation_short t t l             # activation functions                                 (actfunc_short)

########################################################################################################################
### symmetry function generation ( mode 1): 
########################################################################################################################
use_atom_charges                          # use atomic charges for fitting(set always true!)     (luseatomcharges)                      MODE1+2+3+4
test_fraction 0.1                         # threshold for splitting between fitting and test set (splitthres)                           MODE1
#CAUTION: don't forget use_short_forces below (if you want to generate the training files for the forces)
scale_symmetry_functions                   # scale symmetry functions                             (lscalesym)                            MODE2+3+4
center_symmetry_functions                  # remove center of mass of structure function values   (lcentersym)                           MODE2+3+4
repeated_energy_update                     # calculate error of
force_update_scaling  1.0d0                # scaling factor for the force update (negative value means automatic scaling) (scalefactorf) MODE2
#element_decoupled_kalman
nguyen_widrow_weights_short                # initialize short
#nguyen_widrow_weights_ewald               # initialize short
#update_worst_short_energies 0.1d0         # percentage of the worst energies used for update     (worste)                               MODE2
#update_worst_short_forces 0.1d0           # percentage of the worst forces used for update       (worstf)                               MODE2
#steepest_descent_step_energy_short 0.01d0 # step size for steepest descent energy                (steepeststepe)                        MODE2
#steepest_descent_step_force_short 0.01d0  # step size for steepest descent force                 (steepeststepf)                        MODE2
weights_min -1.0                           # minimum value for initial random short range weights
weights_max 1.0                            # maximum value for initial random short range weights
#normalize_nodes                           # normalize input of nodes



########################################################################################################################
### symmetry function definitions (all modes): 
########################################################################################################################
# INFO: not yet implemented in this file
# INFO: symfunction format: reference atom, type, neighbor element 1 (and neighbor element 2), symfunction parameters 
#
# GLOBAL SYMMETRY FUNCTIONS FOR SHORT RANGE NN
#cutoff_type 2
#
# radial N N
symfunction_short N 2 N 0.0000   0.0 11.00                  ! central_atom type neighbor_atom eta rshift funccutoff
symfunction_short N 2 N 0.0120   0.0 11.00                  ! central_atom type neighbor_atom eta rshift funccutoff
symfunction_short N 2 N 0.0300   0.0 11.00                  ! central_atom type neighbor_atom eta rshift funccutoff
symfunction_short N 2 N 0.0620   0.0 11.00                  ! central_atom type neighbor_atom eta rshift funccutoff
symfunction_short N 2 N 0.1300   0.0 11.00                  ! central_atom type neighbor_atom eta rshift funccutoff
symfunction_short N 2 N 0.3000   0.0 11.00                  ! central_atom type neighbor_atom eta rshift funccutoff
symfunction_short N 2 N 1.0000   0.0 11.00                  ! central_atom type neighbor_atom eta rshift funccutoff

Thanks for your help.

**Comment by singraber** [comment]
Well, then the error that caused the MPI abort is the same as in the serial run.. that you have set an incorrect cutoff radius in
```
pair_coeff 6.01
```
This does not match with your symmetry function cutoff radius which is 11.0.. I assume in units of Bohr. Since you are using ``units metal`` you must convert the 11.0 Bohr to Angstrom and use that.

If you omit the ``cutoff_type`` keyword RuNNer will probably fall back to a hard cutoff.. which makes usually no sense.

**Comment by abhirup86** [comment]
Thanks for the help. It seems to work, however, it is now giving me an error message-
`
### NNP EXTRAPOLATION WARNING ### STRUCTURE:      0 ATOM:         1 ELEMENT:  N SYMFUNC:    1 TYPE:  2 VALUE:  8.869E+00 MIN:  5.073E-01 MAX:  9.434E-01
### NNP EXTRAPOLATION WARNING ### STRUCTURE:      0 ATOM:         2 ELEMENT:  N SYMFUNC:    1 TYPE:  2 VALUE:  8.869E+00 MIN:  5.073E-01 MAX:  9.434E-01
### NNP EXTRAPOLATION WARNING ### STRUCTURE:      0 ATOM:         3 ELEMENT:  N SYMFUNC:    1 TYPE:  2 VALUE:  8.869E+00 MIN:  5.073E-01 MAX:  9.434E-01

........
ERROR on proc 0: Too many extrapolation warnings (../pair_nnp.cpp:404)
`

Is that something that could be because of bad geometry or too long a time step? 

I get this when I use the lamps build by the n2p2 package inside `n2p2/src/interface/lammps-nnp/src/lmp_mpi`.
