### ISSUE TITLE
Convert an xyz file into input.data file

### ISSUE THREAD

**Issue by fireballpoint1** [CompPhysVienna/n2p2#89]
**The question**
How can I convert a `.xyz` file containing a single frame to an `input.data` file to be used in a `nnp-predict` ?

**What did you already try?**
I was looking if there a such a conversion in ASE, however I am not sure what the expected output format is call.

**Background**
I am working on linux and wish to calculate the energy prediction for individual frames of an already run simulation using `nnp-predict`. While one of the ways is to run a single step *LAMMPS-n2p2* simulation, it'll require creating multiple `in.lmp` files for each config, Hence, I was wondering if doing it via nnp-predict will be faster and easier and how to prep the input data files ?

**Comment by moabe75** [comment]
I have a simple python script to do this job for me. I would suggest you to do the same. It's very easy to write such a script.

**Comment by singraber** [comment]
I am sorry but I have not considered writing a conversion tool for `xyz` => `input.data` format because `xyz` usually does not contain simulation box information. If you are working on a non-periodic system it should be straightforward to write a conversion tool, e.g. with `awk`. If you have a whole data set converted you could use the tool `nnp-dataset` (instead of `nnp-predict`) because it is designed to predict not just a single configuration but a set and you can use MPI parallelization.

**Comment by xyttyxy** [comment]
I wrote a simple python script recently. 
Just pass in the ASE Atoms object, your energy(ignore the delta_, it's for my own purpose), and the name(used in comment). 
```
def n2p2_data(atoms, delta_energy, name):
        out_str = ''
        out_str += 'begin\n'
        out_str += 'comment ' + name + '\n'

        cell = atoms.get_cell()
        cell_template = 'lattice {:10.6f} {:10.6f} {:10.6f}\n'
        for c in cell:
                out_str += cell_template.format(c[0], c[1], c[2])

        atom_template = 'atom {:10.6f} {:10.6f} {:10.6f} {:2s} {:10.6f} {:10.6f} {:10.6f} {:10.6f} {:10.6f}\n'
        forces = atoms.get_forces()
        for a in atoms:
                force = forces[a.index]
                out_str += atom_template.format(a.position[0], a.position[1], a.position[2],
                                                                                a.symbol, 0.0, 0.0,
                                                                                force[0], force[1], force[2])
        out_str += 'energy {:10.6f}\n'.format(delta_energy)
        out_str += 'charge 0.0\n'
        out_str += 'end\n'

        return out_str
```

**Comment by singraber** [comment]
Thanks for contributing your script here, it may be useful for other users :-)!
