### ISSUE TITLE
Error running latest lammps with the NN potential

### ISSUE THREAD

**Issue by abhirup86** [CompPhysVienna/n2p2#90]
Hi, 

I am trying to use the n2p2-2.1.1 version to run dynamics on the surface using the NN potential already fitted. When I try to run the LAMMPS the same way as examples (Cu2S, H2O) have set up, I get the following error-

ERROR on proc 0: Too many extrapolation warnings (../pair_nnp.cpp:404)

I am attaching the LAMMPS input file (md_lmp.txt, structure.txt), input for training the NN.

[md_lmp.txt](https://github.com/CompPhysVienna/n2p2/files/6070316/md_lmp.txt)
[structure.txt](https://github.com/CompPhysVienna/n2p2/files/6070317/structure.txt)
[input_nn.txt](https://github.com/CompPhysVienna/n2p2/files/6070318/input_nn.txt)

Can you please help me with it? Is it something wrong with my input geometry for LAMMPS or I need to 
retrain the NN with a bigger cutoff.

Thanks,
Abhirup

**Comment by moabe75** [comment]
NNPs have very limited extrapolation capabilities. Therefore, they can easily fail if during the ML MD simulations a structure is met that is outside the training range. It is suggested that the extrapolating structures must be determined and added to the data set. 
I would suggest you to see this [issue](https://github.com/CompPhysVienna/n2p2/issues/62). That might be helpful. 
Also, I would recommend you to look at these papers from Jörg Behler:

https://onlinelibrary.wiley.com/doi/full/10.1002/qua.24890
https://link.springer.com/chapter/10.1007/978-3-030-40245-7_13

**Comment by abhirup86** [comment]
Thank you very much. 

Abhirup
