### ISSUE TITLE
NNP-scaling histogram

### ISSUE THREAD

**Issue by xyttyxy** [CompPhysVienna/n2p2#94]
**The question**
I am a bit confused by what exactly the histogram from `nnp-scaling` is and how it can be used. Sorry if this seems obvious to the experienced users of HDNNPs.

**What did you already try?**
I understand that `scaling.data` shows statistics on symmetry functions over the entire dataset. I dug in the source a bit, is the histogram simply the distribution of result value from one symmetry function on every atom (of the same element) in every structure in the dataset? 

If above is true, then in general the more 'flat' the histogram looks, the better the symmetry function can represent the chemical environments in the dataset, right? If not, how is it to be interpreted?

**Comment by singraber** [comment]
First of all, sorry that there is still lots of lacking documentation...

Actually, the only important file returned from the `nnp-scaling` tool is `scaling.data` which is required for training and prediction. It contains the min, max, mean and sigma values to "normalize" the raw symmetry functions before they are fed to the NN input layer (how they are actually normalized depends on user settings, see [here](https://compphysvienna.github.io/n2p2/topics/keywords.html#center-symmetry-functions) and [here](https://compphysvienna.github.io/n2p2/api/symmetry_function_scaling.html)). Also, if during prediction the [min, max] interval is left an "extrapolation warning" is issued. You have assumed correctly that the statistics is gathered over the entire dataset, i.e. over all atoms of all structures, for each symmetry function separately.

The other files created (`sf.XXX.YYYY.histo`) are just for debugging/testing purposes. To be honest I don't regularly use them.. it may give some insight if the training is not working properly and you suspect that your choice of SFs is not ideal. However, I wouldn't interpret the SF histograms too much.. it's the NNs job to work out what the SF "means" ;-). I don't think one can say that a "flat" distribution is the optimal way of how a SF histogram should look like.. mostly they don't look like this!

**Comment by xyttyxy** [comment]
Thanks. 
In a way you are documenting the code here :)
