### ISSUE TITLE
n2p2 installation on Mac M1

### ISSUE THREAD

**Issue by taidbui** [CompPhysVienna/n2p2#97]
Hi all, 

I am trying to install n2p2 on my Mac M1 but it does not seem to be successful because some packages such as (gsl, eigen, ...) were not recognised even though I have installed these packages using homebrew (e.g., brew install gsl). 

P/S: I tried to install using terminal in Rosetta mode. 

Could you please let me know how to fix this?

Many thanks,
<img width="784" alt="Screenshot 2021-03-13 at 18 45 25" src="https://user-images.githubusercontent.com/28985154/111040734-600fae80-842c-11eb-92ae-f2d903c893d6.png">

**Comment by singraber** [comment]
Hi,

you can try to set the paths manually in the corresponding `makefile.gnu`:

https://github.com/CompPhysVienna/n2p2/blob/3cfe391377d2792ac29baf8394b3dce712afdad2/src/makefile.gnu#L8-L9

Unfortunately, I don't have access to Mac, so I cannot test this.
