### ISSUE TITLE
libnnptrain installation error

### ISSUE THREAD

**Issue by vsumaria** [CompPhysVienna/n2p2#99]
**I am trying to compile n2p2 and facing an issue. I get the following error (after make all command)**

cp GradientDescent.h KalmanFilter.h Updater.h Dataset.h Training.h ../../include
mpic++ -O3 -march=native -std=c++11 -Wno-long-long -g -pedantic-errors -Wall -Wextra -I./ -I../../include/ -I/jet/home/vsumaria/software/gsl/include -I/jet/home/vsumaria/software/anaconda3/pkgs/eigen3-3.3.7-0/include/eigen3 -DEIGEN_USE_BLAS -DEIGEN_DONT_PARALLELIZE -o KalmanFilter.o -c KalmanFilter.cpp
nvc++-Error-Unknown switch: -pedantic-errors
make[1]: *** [makefile:83: KalmanFilter.o] Error 1
make[1]: Leaving directory '/jet/home/vsumaria/software/n2p2/src/libnnptrain'
make: *** [makefile:126: libnnptrain] Error 2

I changed the path to GSL and EIGEN in makefile.gnu and have openmpi and openblas loaded too. Can seem to understand what the error is.

**Comment by abhirup86** [comment]
Hi @vsumaria, I am facing the same issue with n2p2-2.1.2. I am using gsl/2.6:intel-2020 and eigen/3.3.9:intel_flags with intel/2020u4 and openmpi/4.0.5:intel-2020. It seems I can successfully these two-
make libnnp -j 4 COMP=intel MODE=shared 
make libnnpif -j 4 COMP=gnu MODE=shared 

For libnnpif and libnnptrain I could not use intel, I get this error- g++: error: unrecognized command-line option ‘-ipo’. For libnnptrain I also cannot use gnu compiler I get the same error as yours. 

Just wondering if you have solved this issue and if so, how you did. 

Thanks,
Abhirup
